name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# we dont run compression extension
# in regular CI because it is a
# time consuming operation.
# we delegate it to manually triggered CI
# and only run base autobahn tests here.

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        nim --version
        nimble --version
        nimble install -y --depsOnly
        nimble test
        env NIMFLAGS="--mm:refc" nimble test

  autobahn-test:
    # temporary disabled
    if: false # github.event_name == 'push' # || github.event_name == 'pull_request'
    name: "Autobahn test suite"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        websock: [ws, wsc, wss, wssc]
        branch: [version-2-0, version-2-2, devel]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Nim and Nimble
        run: |
          curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
          env MAKE="make -j$(nproc)" NIM_COMMIT=${{ matrix.branch }} \
            QUICK_AND_DIRTY_COMPILER=1 QUICK_AND_DIRTY_NIMBLE=1 CC=gcc \
            bash build_nim.sh nim csources dist/nimble NimBinaries
          echo '${{ github.workspace }}/nim/bin' >> $GITHUB_PATH

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: pypy-2.7

      - name: Setup Autobahn.
        run: |
          sudo apt-get install -y python3-dev
          pip install virtualenv
          pip install markdown2
          virtualenv --python=/usr/bin/python3 autobahn
          source autobahn/bin/activate
          pip install autobahntestsuite txaio==2.1.0 autobahn[twisted,accelerate]==0.10.9 jinja2==2.6 markupsafe==0.19 Werkzeug==0.9.6 klein==0.2.3 pyopenssl service_identity==14.0.0 unittest2==1.1.0 wsaccel==0.6.2
          pip freeze
          nimble install -y --depsOnly

      - name: Generate index.html
        if: matrix.websock == 'ws'
        run: |
          mkdir autobahn/reports
          sed -i "s/COMMIT_SHA_SHORT/${GITHUB_SHA::7}/g" autobahn/index.md
          sed -i "s/COMMIT_SHA/$GITHUB_SHA/g" autobahn/index.md
          markdown2 autobahn/index.md > autobahn/reports/index.html

      - name: Run Autobahn test suite.
        run: |
          source autobahn/bin/activate
          case '${{ matrix.websock }}' in
            ws)
              nim c -d:release examples/server.nim
              examples/server &
              server=$!

              cd autobahn
              wstest --mode fuzzingclient --spec fuzzingclient.json
            ;;
            wsc)
              nim c -d:tls -d:release -o:examples/tls_server examples/server.nim
              examples/tls_server &
              server=$!

              cd autobahn
              wstest --mode fuzzingclient --spec fuzzingclient_tls.json
            ;;
            wss)
              cd autobahn
              wstest --webport=0 --mode fuzzingserver --spec fuzzingserver.json &
              server=$!

              cd ..
              nim c -d:release examples/autobahn_client
              examples/autobahn_client
            ;;
            wssc)
              cd autobahn
              wstest --webport=0 --mode fuzzingserver --spec fuzzingserver_tls.json &
              server=$!

              cd ..
              nim c -d:tls -d:release -o:examples/autobahn_tlsclient examples/autobahn_client
              examples/autobahn_tlsclient
            ;;
          esac

          kill $server

      - name: Upload Autobahn result
        uses: actions/upload-artifact@v4
        with:
          name: autobahn-artifact-${{ matrix.websock }}-${{ matrix.branch }}
          path: ./autobahn/reports

  # Issue related to actions/upload-artifact@v4 immutability
  # Applying Merging multiple artifacts:
  # https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts
  merge-autobahn-artifact:
    # temporary disabled
    if: false
    runs-on: ubuntu-latest
    needs: autobahn-test
    steps:
      - name: Merge Autobahn Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: autobahn-report
          pattern: autobahn-artifact-*

  deploy-test:
    # temporary disabled
    if: false
    name: "Deploy Autobahn results"
    needs: merge-autobahn-artifact
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Download Autobahn reports
        uses: actions/download-artifact@v4
        with:
          name: autobahn-report
          path: ./autobahn_reports

      - name: Deploy autobahn report.
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./autobahn_reports
